optimizer:
  class_path: timm.optim.lamb.Lamb
  init_args:
    lr: 3E-3

# 3E-3 4 GPUs
model:
  class_path: LiereImageClassification
  init_args:
    model_architecture: "liere"
    learning_rate: 1E-4
    patch_size: [16, 16]
    num_classes: 1000
    input_dimensionality: 2
    max_batch_size: 128
    emb_dropout: 0.1
    attn_dropout: 0.1
    # input_type: IMAGES
    num_channels: 3
    replicate_naver: False
    imsize: 224

trainer: 
  max_epochs: 400
  accumulate_grad_batches: 1 #8
  default_root_dir: "/dataNAS/people/sostm/checkpoints/liere_imagenet"
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: "/dataNAS/people/sostm/checkpoints/liere_imagenet"
        save_last: True
        
  logger:
    init_args:
      project: "imagenet"

lr_scheduler:
  class_path: torch.optim.lr_scheduler.CosineAnnealingLR
  init_args:
    T_max: 400

data:
  class_path: Imagenet
  init_args:
    data_dir: "/dataNAS/people/sostm/data/gcp_imagenet/sostm_imagenet"
    per_device_batch_size: 64 # for A100 40GBs
    imsize: 224 #192